#!/bin/bash

DIR=`dirname "$0"`
source $DIR/common.bash
if [[ -n "$1" ]]; then
  MP_VERSION=$1
else
  if [[ $tag == "latest" ]]; then
    MP_VERSION=3.9-SNAPSHOT
  else
    MP_VERSION=$tag
  fi
fi
echo "Downloading midPoint $MP_VERSION"
echo "-----------------------------------------"
curl --output $DIR/midpoint-dist.tar.gz "https://evolveum.com/downloads/midpoint-tier/midpoint-$MP_VERSION-dist.tar.gz"
echo "-----------------------------------------"
echo "Checking the download..."
if tar -tf $DIR/midpoint-dist.tar.gz >/dev/null; then
  echo "OK"
  exit 0
else
  echo "The file was not downloaded correctly"
  exit 1
fi
