gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex2_grouper_data
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex2_grouper_ui
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex2_grouper_ws
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex2_idp
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex2_midpoint_server
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex2_mq
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex2_sources
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex2_targets
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_directory
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_grouper_daemon
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_grouper_data
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_grouper_data_2
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_grouper_ui
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_idp
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_midpoint_server
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_sources
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/complex_targets
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/confluence-server-mysql
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/directory
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/grouper_daemon
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/idp
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/mq
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/rabbitmq
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/sources
gcloud container images delete --quiet gcr.io/rcgrant-kromhout-test/tier
