#!/bin/bash

if [ $REPO_JDBC_URL == "default" ]; then
  case $REPO_DATABASE_TYPE in
	mariadb)
	  echo "jdbc:mariadb://$REPO_HOST:$REPO_PORT/$REPO_DATABASE?characterEncoding=utf8"
	  ;;
	mysql)
	  echo "jdbc:mysql://$REPO_HOST:$REPO_PORT/$REPO_DATABASE?characterEncoding=utf8"
	  ;;
	oracle)
	  echo "jdbc:oracle:thin:@$REPO_HOST:$REPO_PORT/xe"
	  ;;
	postgresql)
	  echo "jdbc:postgresql://$REPO_HOST:$REPO_PORT/$REPO_DATABASE"
	  ;;
	sqlserver)
	  echo "jdbc:sqlserver://$REPO_HOST:$REPO_PORT;database=$REPO_DATABASE"
	  ;;
	*)
	  echo "~~~~~ please supply JDBC URL for your repository ~~~~~"
  esac
else
  echo $REPO_JDBC_URL
fi
