#!/bin/bash

echo "Downloading midPoint 3.9-SNAPSHOT"
echo "-----------------------------------------"
curl --output mp-gr/midpoint-server/midpoint-3.9-SNAPSHOT-dist.tar.gz "https://nexus.evolveum.com/nexus/service/local/artifact/maven/content?r=snapshots&g=com.evolveum.midpoint&a=dist&v=LATEST&c=dist&p=tar.gz"
echo "-----------------------------------------"
echo "Checking the download..."
if tar -tf mp-gr/midpoint-server/midpoint-3.9-SNAPSHOT-dist.tar.gz >/dev/null; then
  echo "OK"
else
  echo "The file was not downloaded correctly"
fi

